repos:
-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest with coverage
        entry: ./run_tests.sh
        language: script
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: flake8
        args: ['--ignore=E203', '--max-line-length=88']